apiVersion: v1
kind: Namespace
metadata:
  name: microservices-lab
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices-lab
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password123
  POSTGRES_DB: inventory_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: microservices-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: microservices-lab
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: microservices-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: microservices-lab
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: microservices-lab
  labels:
    app: inventory-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
        version: v1
    spec:
      containers:
      - name: inventory-api
        image: venkatesh994/order-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-svc"
        - name: DB_NAME
          value: "inventory_db"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: APP_VERSION
          value: "v1"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api-svc
  namespace: microservices-lab
spec:
  selector:
    app: inventory-api
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP